server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
#          文件系统
#          uri: file:D:/server-config
#          HTTP
#          uri: https://github.com/fzbdeqq/config-repo
          uri: https://github.com/fzbdeqq/{application}
          timeout: 5
#          skip-ssl-validation: true